name: example
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  languagetool_text_field: 
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  solid_lints: ^0.0.13


flutter:
  uses-material-design: true

  