name: app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  language_tool: ^2.1.1
  languagetool_textfield:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.14

flutter:
  uses-material-design: true
